package com.pkuhjw.pkukaola.dao;

import com.pkuhjw.pkukaola.domain.PkukaolaUser;
import com.pkuhjw.pkukaola.domain.PkukaolaUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PkukaolaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    long countByExample(PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int deleteByExample(PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int insert(PkukaolaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int insertSelective(PkukaolaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    PkukaolaUser selectOneByExample(PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    PkukaolaUser selectOneByExampleSelective(@Param("example") PkukaolaUserExample example, @Param("selective") PkukaolaUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    List<PkukaolaUser> selectByExampleSelective(@Param("example") PkukaolaUserExample example, @Param("selective") PkukaolaUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    List<PkukaolaUser> selectByExample(PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    PkukaolaUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PkukaolaUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    PkukaolaUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    PkukaolaUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PkukaolaUser record, @Param("example") PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PkukaolaUser record, @Param("example") PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PkukaolaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PkukaolaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") PkukaolaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkukaola_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}